### ISSUE TITLE
Biomes OP API crash

### ISSUE THREAD

**Issue by nanakisan** [DrasticDemise/Terrain-Crystals-Addons#3]
Seems your mod has outdated API or is simply not using the right one.

https://paste.ee/p/TRpIj

I could be translating the crash report incorrectly. But as noted in the mods listing section I am using the Release version for 1.10.2 of Biomes OP. The same for your mod as well.

**Comment by DrasticDemise** [comment]
Uhhh are you using the latest release of both mods? I believe I fixed an issue with the API interaction in the latest release, specifically for BOPWoods

**Comment by nanakisan** [comment]
Let me have a look see. I am getting a out of date notice in my instance for Terrain Crystals so I wonder if that is the case.

**Comment by nanakisan** [comment]
Just checked and I compared all versions posted on Curseforge. They're all the absolute latest according to those repos. Are you using a Jenkins build server that isn't listed with more recent versions?

**Comment by baileyholl** [comment]
Is this the build you are running?
 https://minecraft.curseforge.com/projects/terrain-crystals/files/2327198

**Comment by nanakisan** [comment]
Yep that is the one. Even compare it to the version number in the crashlog. It's the same.

**Comment by baileyholl** [comment]
https://gyazo.com/005694a1a593e884bc7b5aa04f1f1db8

Running the latest beta build of BoP and the latest builds of both Terrain Crystals addon's and Terrain Crystals launches just fine.

**Comment by nanakisan** [comment]
Seems that specific version of Biomes OP was our culprit. version 2068 as my instance just loaded up fine and dandy when I switched to 2085.
